### ISSUE TITLE
Nokogiri::CSS::SyntaxError: unexpected '$' after ' '

### ISSUE THREAD

**Issue by yashwinkumar** [sparklemotion/mechanize#439] opened 2015-08-15 09:36 UTC
````gem 'mechanize', '~> 2.7.3'````

Getting following error while doing `search` on the page
````
Nokogiri::CSS::SyntaxError: unexpected '$' after ' '
from /home/user/.rvm/gems/ruby-2.2.1/gems/nokogiri-1.6.6.2/lib/nokogiri/css/parser_extras.rb:87:in `on_error'
`````

**Comment by leejarvis** [comment] 2015-08-16 07:42
Could you provide code to reproduce this issue please?

**Comment by yashwinkumar** [comment] 2015-08-17 06:53
````
require 'mechanize'
mechanize = Mechanize.new
page = mechanize.get("http://www.example.com/")
latest = page.search(".item ")
````
I got that fixed. I kept extra space after while searching with className.

**Comment by leejarvis** [comment] 2015-08-17 07:24
> I kept extra space after while searching with className.

Why? That's what's causing the `SyntaxError`. It's not valid.

**Comment by yashwinkumar** [comment] 2015-08-18 18:00
Yes. Extra space caused error. I'm positive about it. I double checked it.
Check in the screenshot, before and after.
![screenshot from 2015-08-18 23 28 03](https://cloud.githubusercontent.com/assets/2732153/9338166/e20678a8-4600-11e5-9e2b-4b2dce123f44.png)

**Comment by leejarvis** [comment] 2015-08-18 19:29
Yes that's correct. I was asking why you have it. This isn't an issue since you can just remove the space because it's invalid syntax. Closing this ticket.

**Closed by leejarvis** 2015-08-18 19:29 UTC
