### ISSUE TITLE
NoMethodError from agent.rb:648

### ISSUE THREAD

**Issue by committance** [sparklemotion/mechanize#420] opened 2015-02-10 10:06 UTC
Hi,
This code

require 'mechanize'
agent = Mechanize.new    

agent.keep_alive = false
agent.open_timeout = 2
agent.read_timeout = 2
agent.ignore_bad_chunking = true
agent.gzip_enabled = false

url = 'http:%5C%5Cwww.scouts.org.uk'

agent.head(url)

leads to thi Error:

~/.rvm/gems/ruby-head/gems/mechanize-2.7.3/lib/mechanize/http/agent.rb:648:in `resolve': undefined method`length' for nil:NilClass (NoMethodError)

```
from ~/.rvm/gems/ruby-head/gems/mechanize-2.7.3/lib/mechanize/http/agent.rb:223:in `fetch'
from ~/.rvm/gems/ruby-head/gems/mechanize-2.7.3/lib/mechanize.rb:459:in `head
```

I'm running mecahnize 2.7.3 and ruby 2.3.0dev. Will it be fixed?

**Comment by giglemad** [comment] 2017-03-30 22:36
%5C is the escape code for backslash, not forward slash. This is not a bug, maintainers might want to close this

**Closed** 2017-03-31 01:07 UTC

**Comment by knu** [comment] 2017-03-31 01:10
Thanks, I fixed it so it would raise ArgumentError instead.
